/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogExportPolicy.java
 *
 * Created on 22 févr. 2012, 18:18:50
 */
package newmotorbac.dialog;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import orbac.AbstractOrbacPolicy;
import orbac.COrbacCore;
import orbac.exception.COrbacException;

/**
 *
 * @author fabien
 */
public class JDialogExportPolicy extends javax.swing.JDialog {

    public boolean canceled = false;
    private AbstractOrbacPolicy policyToExport;
    // path where to export
    private File path;
    
    /** Creates new form JDialogExportPolicy */
    public JDialogExportPolicy(java.awt.Frame parent, boolean modal, AbstractOrbacPolicy policyToExport) {
        super(parent, modal);
        initComponents();
        
        this.policyToExport = policyToExport;

        // get the orbac core instance
        COrbacCore core = COrbacCore.GetTheInstance();
        // fill combo box
        for ( String c : core.GetSupportedPolicyTypes() )
        {
            // do not add implementation corresponding to the exported policy
            if ( c.equals(policyToExport.getClass().toString()) )
                continue;
            jComboBoxImplementation.addItem(c);
        }
        jComboBoxImplementation.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPolicyName = new javax.swing.JLabel();
        jTextFieldPolicyName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxImplementation = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        JTextFieldPath = new javax.swing.JTextField();
        jButtonExport = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonChoosePath = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(newmotorbac.NewMotorbacApp.class).getContext().getResourceMap(JDialogExportPolicy.class);
        jLabelPolicyName.setText(resourceMap.getString("jLabelPolicyName.text")); // NOI18N
        jLabelPolicyName.setName("jLabelPolicyName"); // NOI18N

        jTextFieldPolicyName.setName("jTextFieldPolicyName"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jComboBoxImplementation.setName("jComboBoxImplementation"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        JTextFieldPath.setName("JTextFieldPath"); // NOI18N

        jButtonExport.setText(resourceMap.getString("jButtonExport.text")); // NOI18N
        jButtonExport.setName("jButtonExport"); // NOI18N
        jButtonExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportActionPerformed(evt);
            }
        });

        jButtonCancel.setText(resourceMap.getString("jButtonCancel.text")); // NOI18N
        jButtonCancel.setName("jButtonCancel"); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonChoosePath.setIcon(resourceMap.getIcon("jButtonChoosePath.icon")); // NOI18N
        jButtonChoosePath.setText(resourceMap.getString("jButtonChoosePath.text")); // NOI18N
        jButtonChoosePath.setName("jButtonChoosePath"); // NOI18N
        jButtonChoosePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChoosePathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabelPolicyName))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxImplementation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(JTextFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonChoosePath)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonExport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPolicyName)
                    .addComponent(jTextFieldPolicyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxImplementation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JTextFieldPath)
                        .addComponent(jLabel2))
                    .addComponent(jButtonChoosePath, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExport)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        canceled = true;
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportActionPerformed
        try {
            if ( jTextFieldPolicyName.getText().equals("") )
            {
                JOptionPane.showMessageDialog(this, "A policy name must be specified", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if ( JTextFieldPath.getText().equals("") )
            {
                JOptionPane.showMessageDialog(this, "An export path must be specified", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            // translate policy
            AbstractOrbacPolicy p = COrbacCore.GetTheInstance().TranslatePolicy(policyToExport, jComboBoxImplementation.getSelectedItem().toString());
            try {
                // save it in the specified file
                p.WritePolicyFile(JTextFieldPath.getText(), null);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (COrbacException e) {
            JOptionPane.showMessageDialog(this, e, "Error while exporting policy", JOptionPane.WARNING_MESSAGE);
            //Logger.getLogger(JDialogExportPolicy.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jButtonExportActionPerformed

    private void jButtonChoosePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChoosePathActionPerformed
        // create the file chooser and set the title
        // get working directory
        File file = new File(".");
        String absPath = "";
        try
        {
            absPath = file.getCanonicalPath();
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }
        JFileChooser chooser = new JFileChooser(absPath);
        chooser.setDialogTitle("Select exported policy path");
        if ( chooser.showSaveDialog(this) == JFileChooser.CANCEL_OPTION ) 
            return;
        
        // get the selected file
        path = chooser.getSelectedFile();
        JTextFieldPath.setText(path.getAbsolutePath());
    }//GEN-LAST:event_jButtonChoosePathActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField JTextFieldPath;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonChoosePath;
    private javax.swing.JButton jButtonExport;
    public javax.swing.JComboBox jComboBoxImplementation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPolicyName;
    public javax.swing.JTextField jTextFieldPolicyName;
    // End of variables declaration//GEN-END:variables
}
