package newmotorbac.dialog;


import javax.swing.JOptionPane;
import orbac.AbstractOrbacPolicy;
import orbac.exception.COrbacException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogAddContext.java
 *
 * Created on May 26, 2011, 5:11:22 PM
 */

/**
 *
 * @author fabien
 */
public class jDialogAddEntityDefinition extends javax.swing.JDialog {

    public boolean canceled = false;
    // associated policy
    private AbstractOrbacPolicy policy;

    /** Creates new form jDialogAddEntityDefinition */
    public jDialogAddEntityDefinition(java.awt.Frame parent, boolean modal, AbstractOrbacPolicy policy) {
        super(parent, modal);
        initComponents();

        setTitle("Add a new entity definition to policy");

        // save given variable
        this.policy = policy;

        // stupid trick to fill the abstract entity combo box
        jComboBoxEntityType.setSelectedIndex(1);
        jComboBoxEntityType.setSelectedIndex(0);

        // TODO: fill entity definition types
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxDefinitionLanguage = new javax.swing.JComboBox();
        jButtonCancel = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEntityDefinitionName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabelAssociatedEntity = new javax.swing.JLabel();
        jComboBoxEntityType = new javax.swing.JComboBox();
        jComboBoxEntity = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(413, 170));
        setName("Form"); // NOI18N
        setResizable(false);

        jComboBoxDefinitionLanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Prova (declarative)", "BeanShell (imperative)" }));
        jComboBoxDefinitionLanguage.setName("jComboBoxDefinitionLanguage"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(newmotorbac.NewMotorbacApp.class).getContext().getResourceMap(jDialogAddEntityDefinition.class);
        jButtonCancel.setText(resourceMap.getString("jButtonCancel.text")); // NOI18N
        jButtonCancel.setName("jButtonCancel"); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonOk.setText(resourceMap.getString("jButtonOk.text")); // NOI18N
        jButtonOk.setName("jButtonOk"); // NOI18N
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jTextFieldEntityDefinitionName.setText(resourceMap.getString("jTextFieldEntityDefinitionName.text")); // NOI18N
        jTextFieldEntityDefinitionName.setName("jTextFieldEntityDefinitionName"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabelAssociatedEntity.setText(resourceMap.getString("jLabelAssociatedEntity.text")); // NOI18N
        jLabelAssociatedEntity.setName("jLabelAssociatedEntity"); // NOI18N

        jComboBoxEntityType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "role definition", "activity definition", "view definition" }));
        jComboBoxEntityType.setName("jComboBoxEntityType"); // NOI18N
        jComboBoxEntityType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEntityTypeItemStateChanged(evt);
            }
        });

        jComboBoxEntity.setName("jComboBoxEntity"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jTextFieldEntityDefinitionName, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAssociatedEntity)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDefinitionLanguage, javax.swing.GroupLayout.Alignment.TRAILING, 0, 243, Short.MAX_VALUE)
                            .addComponent(jComboBoxEntity, 0, 243, Short.MAX_VALUE)
                            .addComponent(jComboBoxEntityType, 0, 243, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEntityDefinitionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxEntityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEntity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAssociatedEntity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDefinitionLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        canceled = true;
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // check if an entity definition name has been specified
    	if ( jTextFieldEntityDefinitionName.getText().equals("") )
    	{
            JOptionPane.showMessageDialog(this, "You must specify an entity definition name");
            return;
    	}
        dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jComboBoxEntityTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEntityTypeItemStateChanged
        // display entity list based on the selected entity type
        jComboBoxEntity.removeAllItems();
        try
        {
            switch ( jComboBoxEntityType .getSelectedIndex() )
            {
                case 0:// roles
                    for ( String r : policy.GetRolesList(false) )
                        jComboBoxEntity.addItem(r);
                    jLabelAssociatedEntity.setText("Associated role:");
                    break;
                case 1:// activities
                    for ( String a : policy.GetActivitiesList(false) )
                        jComboBoxEntity.addItem(a);
                    jLabelAssociatedEntity.setText("Associated activity:");
                    break;
                case 2:// views
                    for ( String v : policy.GetViewsList(true) )
                        jComboBoxEntity.addItem(v);
                    jLabelAssociatedEntity.setText("Associated view:");
                    break;
            }
        }
        catch ( COrbacException e )
        {
            System.out.println(e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxEntityTypeItemStateChanged

    public String GetEntityDefinitionName()
    {
        return jTextFieldEntityDefinitionName.getText();
    }
    public String GetEntityDefinitionType()
    {
        String selectedType = (String)jComboBoxEntityType.getSelectedItem();
        String languageType = (String)jComboBoxDefinitionLanguage.getSelectedItem();
        // TODO: change this when the entity definition factory implementation is ready
        if ( selectedType.equals("role definition") )
        {
            if ( languageType.equals("Prova (declarative)") ) return AbstractOrbacPolicy.TYPE_PROVA_ROLE_DEFINITION;
            else if ( languageType.equals("BeanShell (imperative)") ) return AbstractOrbacPolicy.TYPE_BEANSHELL_ROLE_DEFINITION;
            else if ( languageType.equals("Threat") ) return AbstractOrbacPolicy.TYPE_THREAT_ROLE_DEFINITION;
        }
        else if ( selectedType.equals("activity definition") )
        {
            if ( languageType.equals("Prova (declarative)") ) return AbstractOrbacPolicy.TYPE_PROVA_ACTIVITY_DEFINITION;
            else if ( languageType.equals("BeanShell (imperative)") ) return AbstractOrbacPolicy.TYPE_BEANSHELL_ACTIVITY_DEFINITION;
            else if ( languageType.equals("Threat") ) return AbstractOrbacPolicy.TYPE_THREAT_ACTIVITY_DEFINITION;
        }
        else if ( selectedType.equals("view definition") )
        {
            if ( languageType.equals("Prova (declarative)") ) return AbstractOrbacPolicy.TYPE_PROVA_VIEW_DEFINITION;
            else if ( languageType.equals("BeanShell (imperative)") ) return AbstractOrbacPolicy.TYPE_BEANSHELL_VIEW_DEFINITION;
            else if ( languageType.equals("Threat") ) return AbstractOrbacPolicy.TYPE_THREAT_VIEW_DEFINITION;
        }
        return "";
    }
    public String GetEntityDefinitionLanguage()
    {
        return (String)jComboBoxDefinitionLanguage.getSelectedItem();
    }
    public String GetEntityName()
    {
        return (String)jComboBoxEntity.getSelectedItem();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JComboBox jComboBoxDefinitionLanguage;
    private javax.swing.JComboBox jComboBoxEntity;
    private javax.swing.JComboBox jComboBoxEntityType;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAssociatedEntity;
    private javax.swing.JTextField jTextFieldEntityDefinitionName;
    // End of variables declaration//GEN-END:variables

}
