/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogAddConcreteEntity.java
 *
 * Created on May 10, 2011, 7:07:24 PM
 */

package newmotorbac.dialog;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author fabien
 */
public class jDialogAddAbstractEntity extends javax.swing.JDialog {

    public boolean canceled = false;
    protected Object headers[] = {"", ""};
    NewConcreteEntityTableModel model;

    /** Creates new form JDialogAddConcreteEntity */
    public jDialogAddAbstractEntity(java.awt.Frame parent, String entityTypeStr, Set<String> entities, String superEntity, String org, boolean modal) {
        super(parent, modal);
        initComponents();

        // set title
        setTitle("Create new " + entityTypeStr + " in organization " + org);
        // set label
        jLabelEntityName.setText(entityTypeStr + " name:");
        // set headers
        headers[1] = entityTypeStr;
        headers[0] = "sub-" + entityTypeStr + " of";

        // fill table
        model = new NewConcreteEntityTableModel(headers, 0);
        jTableSuperEntities.setModel(model);
        for ( String o : entities )
        {
            Object[] row = new Object[2];
            row[0] = (superEntity == null) ? false : o.equals(superEntity);
            row[1] = o;
            model.addRow(row);
        }

         // set class selection column width
        jTableSuperEntities.getColumn(headers[0]).setMinWidth(150);
        jTableSuperEntities.getColumn(headers[0]).setMaxWidth(150);

        getRootPane().setDefaultButton(jButtonOk);
    }

    // constructor used when editing an entity
    public jDialogAddAbstractEntity(java.awt.Frame parent, String entityTypeStr, String entityName, Set<String> entities, Set<String> superEntities, boolean modal) {
        super(parent, modal);
        initComponents();

        // set title
        setTitle("Edit " + entityTypeStr);

        // set entity name
        jTextFieldEntityName.setText(entityName);

        // fill table and select classes
        headers[0] = "sub-" + entityTypeStr + " of";
        model = new NewConcreteEntityTableModel(headers, 0);
        jTableSuperEntities.setModel(model);
        for ( String e : entities )
        {
            Object[] row = new Object[2];
            row[0] = superEntities.contains(e);
            row[1] = e;
            model.addRow(row);
        }

         // set class selection column width
        jTableSuperEntities.getColumn(headers[0]).setMinWidth(150);
        jTableSuperEntities.getColumn(headers[0]).setMaxWidth(150);
    }

    public Set<String> GetSuperEntities()
    {
        HashSet<String> classes = new HashSet<String>();
        for ( int i = 0; i < model.getRowCount(); i++)
        {
            Boolean b = (Boolean)model.getValueAt(i, 0);
            if ( b )
                classes.add((String)model.getValueAt(i, 1));
        }
        return classes;
    }
    public String GetEntityName()
    {
        return jTextFieldEntityName.getText();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEntityName = new javax.swing.JLabel();
        jTextFieldEntityName = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonOk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSuperEntities = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Form"); // NOI18N
        setResizable(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(newmotorbac.NewMotorbacApp.class).getContext().getResourceMap(jDialogAddAbstractEntity.class);
        jLabelEntityName.setText(resourceMap.getString("jLabelEntityName.text")); // NOI18N
        jLabelEntityName.setName("jLabelEntityName"); // NOI18N

        jTextFieldEntityName.setText(resourceMap.getString("jTextFieldEntityName.text")); // NOI18N
        jTextFieldEntityName.setName("jTextFieldEntityName"); // NOI18N

        jButtonCancel.setText(resourceMap.getString("jButtonCancel.text")); // NOI18N
        jButtonCancel.setName("jButtonCancel"); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonOk.setText(resourceMap.getString("jButtonOk.text")); // NOI18N
        jButtonOk.setName("jButtonOk"); // NOI18N
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTableSuperEntities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "sub-organization of", "organization"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSuperEntities.setName("jTableSuperEntities"); // NOI18N
        jTableSuperEntities.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableSuperEntities);
        jTableSuperEntities.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTableSuperEntities.getColumnModel().getColumn(0).setMaxWidth(150);
        jTableSuperEntities.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTableSuperEntities.columnModel.title0")); // NOI18N
        jTableSuperEntities.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTableSuperEntities.columnModel.title1")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelEntityName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEntityName, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEntityName)
                    .addComponent(jTextFieldEntityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOk))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // check if an entity name has been specified
    	if ( jTextFieldEntityName.getText().equals("") )
    	{
            JOptionPane.showMessageDialog(this, "You must specify an entity name");
            return;
    	}
        dispose();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        canceled = true;
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelEntityName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSuperEntities;
    private javax.swing.JTextField jTextFieldEntityName;
    // End of variables declaration//GEN-END:variables
}
