/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelConflicts.java
 *
 * Created on May 5, 2011, 5:33:46 PM
 */

package newmotorbac;

import newmotorbac.util.OrbacPolicyContext;

/**
 *
 * @author fabien
 */
public class PanelConflicts extends javax.swing.JPanel {
    // policy context
    OrbacPolicyContext thisContext;
    // tabs
    private PanelAbstractConflicts      panelAbstractConflicts;
    private PanelConcreteConflicts      panelConcreteConflicts;
    private PanelSeparationConstraints  panelSeparationConstraints;
    private PanelRulesPriorities        panelRulesPriorities;

    /** Creates new form PanelConflicts */
    public PanelConflicts(OrbacPolicyContext thisContext) {
        initComponents();

        // store context
        this.thisContext = thisContext;

        // create tabs
        panelAbstractConflicts = new PanelAbstractConflicts(thisContext);
        panelConcreteConflicts = new PanelConcreteConflicts(thisContext);
        panelSeparationConstraints = new PanelSeparationConstraints(thisContext);
        panelRulesPriorities = new PanelRulesPriorities(thisContext);
        // add them
        jTabbedPaneConflicts.addTab("Abstract conflicts", panelAbstractConflicts);
        jTabbedPaneConflicts.addTab("Concrete conflicts", panelConcreteConflicts);
        if ( thisContext.thePolicy.IsSeparationConstraintImplemented() )
            jTabbedPaneConflicts.addTab("Separation constraints", panelSeparationConstraints);
        jTabbedPaneConflicts.addTab("Rules priorities", panelRulesPriorities);
        // store them in context
        thisContext.panelConflicts = this;
        thisContext.panelAbstractConflicts = panelAbstractConflicts;
        thisContext.panelConcreteConflicts = panelConcreteConflicts;
        thisContext.panelSeparationConstraints = panelSeparationConstraints;
        thisContext.panelRulesPriorities = panelRulesPriorities;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneConflicts = new javax.swing.JTabbedPane();

        setName("Form"); // NOI18N

        jTabbedPaneConflicts.setName("jTabbedPaneConflicts"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneConflicts, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneConflicts, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void UpdateTabs()
    {
        panelAbstractConflicts.UpdateConflictTable();
        panelConcreteConflicts.UpdateConflictTable();
        panelSeparationConstraints.UpdateSeparationConstraintTable();
        panelRulesPriorities.UpdateRulePrioritiesTable();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPaneConflicts;
    // End of variables declaration//GEN-END:variables

}
